### ISSUE TITLE
As an International Agent, I want the portal to have a regularly updating news section about the promotion related events and webinars, so that we can login and be aware of them and can inform and encourage the prospective students to attend.

### ISSUE THREAD

**Issue by AxelZublena** [404GNF/International-Agents-Portal#40]
GIVEN: The International Agent is on the welcome page of the website
WHEN: The International Agent clicks on the news section
THEN: The International Agent can see all news which is up to date
WHEN: The International Agent can see only out of date news
THEN: The International Agent sends report about no updating the news section

**Comment by BogomilDochev** [comment]
Validated but not required
