### ISSUE TITLE
Functional Design for error page

### ISSUE THREAD

**Issue by gaut0003** [404GNF/International-Agents-Portal#49]

**Comment by gaut0003** [comment]
![Untitled Diagram](https://user-images.githubusercontent.com/70516855/115669088-30679680-a348-11eb-82fb-967ed8bd9606.png)

**Comment by gaut0003** [comment]
![image](https://user-images.githubusercontent.com/70516855/115669383-7de40380-a348-11eb-86b3-9a6bf6a4fb2f.png)

**Comment by gaut0003** [comment]
![image](https://user-images.githubusercontent.com/70516855/115671627-02d01c80-a34b-11eb-872a-0f25d2105231.png)

**Comment by AxelZublena** [comment]
![Usability - Wireflows](https://user-images.githubusercontent.com/70519900/115680163-9c9bc780-a353-11eb-90a2-ff18e042a65e.png)

**Comment by TophatPigeonno** [comment]
![image](https://user-images.githubusercontent.com/70545333/115711045-56eef700-a373-11eb-943e-c0c0347ebb05.png)
