### ISSUE TITLE
Technical Design for error page

### ISSUE THREAD

**Issue by gaut0003** [404GNF/International-Agents-Portal#50]

**Comment by gaut0003** [comment]
Leave comment if done

**Comment by gaut0003** [comment]
[Picture](https://cdn.discordapp.com/attachments/818429091333406744/834046587722006528/unknown.png)

**Comment by gaut0003** [comment]
![image](https://user-images.githubusercontent.com/70516855/115400619-c9cc6680-a1e9-11eb-8815-236e721506dd.png)

**Comment by AxelZublena** [comment]
![404 Sequence Diagram](https://user-images.githubusercontent.com/70519900/115680061-83931680-a353-11eb-9bac-6a3c61a179ee.png)
![500 Sequence Diagram](https://user-images.githubusercontent.com/70519900/115680105-8db51500-a353-11eb-9088-ee531ce26b3a.png)

**Comment by TophatPigeonno** [comment]
![sequence diagram](https://user-images.githubusercontent.com/70545333/115727039-8b6aaf00-a383-11eb-9c55-dd963f165795.png)
![sequence diagram (1)](https://user-images.githubusercontent.com/70545333/115727478-ea302880-a383-11eb-825a-f3942716fda1.png)
